# Generated by Django 5.1.7 on 2025-09-18 21:06

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_photo_path),
        ),
    ]
