# Generated by Django 5.1.7 on 2025-10-26 05:52

import apps.academics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('qr_step_seconds', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.courseassignment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.room')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.academics.models.student_profile_photo_path)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.courseassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'unique_together': {('student', 'course_assignment')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('face', 'Face'), ('qr', 'QR')], max_length=10)),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('face_conf', models.FloatField(blank=True, null=True)),
                ('geo_ok', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Rejected', 'Rejected')], max_length=12)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.student')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='academics_a_session_9ca7ee_idx'), models.Index(fields=['student'], name='academics_a_student_b5ab74_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
