# Generated by Django 5.1.7 on 2025-10-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_student_enrollment_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
