# Generated by Django 5.1.7 on 2025-10-30 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_student_roll_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseassignment',
            old_name='active',
            new_name='allow_self_enroll',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='capacity',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='enrollment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.professor'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='section',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='term',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('stopped', 'Stopped')], default='scheduled', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.department'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='academics_a_status_f269ae_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['course_assignment'], name='academics_s_course__98ad17_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time', 'end_time'], name='academics_s_start_t_dd836b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='academics_s_departm_00517d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_no'], name='academics_s_roll_no_d3daf7_idx'),
        ),
    ]
