# Generated by Django 5.1.7 on 2025-11-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_active_courseassignment_allow_self_enroll_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='academics_s_course__98ad17_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='academics_s_start_t_dd836b_idx',
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'start_time'], name='academics_s_status_3a9544_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'end_time'], name='academics_s_status_01785f_idx'),
        ),
    ]
