# Generated by Django 5.1.7 on 2025-11-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_session_academics_s_course__98ad17_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('face', 'Face'), ('qr', 'QR'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Rejected', 'Rejected'), ('Excused', 'Excused'), ('Absent', 'Absent')], default='Absent', max_length=12),
        ),
    ]
