# Generated by Django 5.1.7 on 2025-11-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_attendance_note_alter_attendance_method_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='academics_s_status_3a9544_idx',
        ),
        migrations.RemoveIndex(
            model_name='session',
            name='academics_s_status_01785f_idx',
        ),
        migrations.AddField(
            model_name='session',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
