# Generated by Django 5.1.7 on 2025-11-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_session_academics_s_course__98ad17_idx_and_more'),
        ('biometrics', '0002_alter_userembeddingtemplate_id_alter_userface_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfaceembedding',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='academics.student'),
        ),
    ]
