# Generated by Django 5.1.7 on 2025-11-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_userfaceembedding_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfaceembedding',
            name='student',
        ),
    ]
